try {
    const value =12;
    if(value > 10){
        console.log("try")
    }
} catch{
    console.log("catch")
}finally{
    console.log("finally")
}